[package]
name = "pixelize-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
onnxruntime = "0.0.14"
ndarray = "0.15.1"
num_cpus = "1.0"
